/* Generated config file */

module.exports = {
  "label": "Lʉgbàràti",
  "code": "lb",
  "layout": {
    "style": "table"
  },
  "phonemes": [
    {'id': 1,'label': 'Intro', 'key': 'Intro'}, 
{'id': 2,'label': 'Aa', 'key': 'Aa'}, 
{'id': 3,'label': 'Bb', 'key': 'Bb'}, 
{'id': 4,'label': '\'B\'b', 'key': '\'B\'b'}, 
{'id': 5,'label': 'Cc', 'key': 'Cc'}, 
{'id': 6,'label': 'Dd', 'key': 'Dd'}, 
{'id': 7,'label': '\'D\'d', 'key': '\'D\'d'}, 
{'id': 8,'label': 'Drdr', 'key': 'Drdr'}, 
{'id': 9,'label': 'Ee', 'key': 'Ee'}, 
{'id': 10,'label': 'Ff', 'key': 'Ff'}, 
{'id': 11,'label': 'Gg', 'key': 'Gg'}, 
{'id': 12,'label': 'Gbgb', 'key': 'Gbgb'}, 
{'id': 13,'label': 'Hh', 'key': 'Hh'}, 
{'id': 14,'label': 'Hwhw', 'key': 'Hwhw'}, 
{'id': 15,'label': '\'', 'key': '\''}, 
{'id': 16,'label': 'Ii', 'key': 'Ii'}, 
{'id': 17,'label': 'ᵻɨɨ', 'key': 'ᵻɨɨ'}, 
{'id': 18,'label': 'Jj', 'key': 'Jj'}, 
{'id': 19,'label': 'Kk', 'key': 'Kk'}, 
{'id': 20,'label': 'Kpkp', 'key': 'Kpkp'}, 
{'id': 21,'label': 'Ll', 'key': 'Ll'}, 
{'id': 22,'label': 'Mm', 'key': 'Mm'}, 
{'id': 23,'label': 'Mbmb', 'key': 'Mbmb'}, 
{'id': 24,'label': 'Mgbmgb', 'key': 'Mgbmgb'}, 
{'id': 25,'label': 'Mvmv', 'key': 'Mvmv'}, 
{'id': 26,'label': 'Nn', 'key': 'Nn'}, 
{'id': 27,'label': 'Ndnd', 'key': 'Ndnd'}, 
{'id': 28,'label': 'Ndrndr', 'key': 'Ndrndr'}, 
{'id': 29,'label': 'Ngng', 'key': 'Ngng'}, 
{'id': 30,'label': 'Nyny', 'key': 'Nyny'}, 
{'id': 31,'label': 'Nznz', 'key': 'Nznz'}, 
{'id': 32,'label': 'Ŋŋ', 'key': 'Ŋŋ'}, 
{'id': 33,'label': 'Oo', 'key': 'Oo'}, 
{'id': 34,'label': 'Pp', 'key': 'Pp'}, 
{'id': 35,'label': 'Rr', 'key': 'Rr'}, 
{'id': 36,'label': 'Ss', 'key': 'Ss'}, 
{'id': 37,'label': 'Tt', 'key': 'Tt'}, 
{'id': 38,'label': 'Trtr', 'key': 'Trtr'}, 
{'id': 39,'label': 'Uu', 'key': 'Uu'}, 
{'id': 40,'label': 'Ʉʉ', 'key': 'Ʉʉ'}, 
{'id': 41,'label': 'Vv', 'key': 'Vv'}, 
{'id': 42,'label': 'Ww', 'key': 'Ww'}, 
{'id': 43,'label': '\'W\'w', 'key': '\'W\'w'}, 
{'id': 44,'label': 'Yy', 'key': 'Yy'}, 
{'id': 45,'label': '\'Y\'y', 'key': '\'Y\'y'}, 
{'id': 46,'label': 'Zz', 'key': 'Zz'}, 
{'id': 47,'label': 'Outro', 'key': 'Outro'}
  ]
};