/* Generated config file */

module.exports = {
  "label": "Luganda",
  "code": "lg",
  "layout": {
    "style": "table"
  },
  "phonemes": [{
    "id": 1,
    "label": "Intro",
    "key": "Intr"
  }, {
    "id": 2,
    "label": "Aa",
    "key": "Aa"
  }, {
    "id": 3,
    "label": "Bb",
    "key": "Bb"
  }, {
    "id": 4,
    "label": "Cc",
    "key": "Cc"
  }, {
    "id": 5,
    "label": "Dd",
    "key": "Dd"
  }, {
    "id": 6,
    "label": "Ee",
    "key": "Ee"
  }, {
    "id": 7,
    "label": "Ff",
    "key": "Ff"
  }, {
    "id": 8,
    "label": "Gg",
    "key": "Gg"
  }, {
    "id": 9,
    "label": "Ii",
    "key": "Ii"
  }, {
    "id": 10,
    "label": "Jj",
    "key": "Jj"
  }, {
    "id": 11,
    "label": "Kk",
    "key": "Kk"
  }, {
    "id": 12,
    "label": "Ll_Rr",
    "key": "Ll_Rr"
  }, {
    "id": 13,
    "label": "Mm",
    "key": "Mm"
  }, {
    "id": 14,
    "label": "Nn",
    "key": "Nn"
  }, {
     "id": 15,
    "label": "ŋ_ng",
    "key": "ŋ_ng"
  }, {
    "id": 16,
    "label": "Ny",
    "key": "Ny"
  }, {
    "id": 17,
    "label": "Oo",
    "key": "Oo"
  }, {
    "id": 18,
    "label": "Pp",
    "key": "Pp"
  }, {
    "id": 19,
    "label": "Ss",
    "key": "Ss"
  }, {
    "id": 20,
    "label": "Tt",
    "key": "Tt"
  }, {
    "id": 21,
    "label": "Uu",
    "key": "Uu"
  }, {
    "id": 22,
    "label": "Vv",
    "key": "Vv"
  }, {
    "id": 23,
    "label": "Ww",
    "key": "Ww"
  }, {
    "id": 24,
    "label": "Yy",
    "key": "Yy"
  }, {
    "id": 25,
    "label": "Zz",
    "key": "Zz"
  }]
};