/* Generated config file */

module.exports = {
  "label": "Lëb Acoli",
  "code": "la",
  "layout": {
    "style": "table"
  },
  "phonemes": [{
    "id": 1,
    "label": "Intro",
    "key": "Intro"
  }, {
    "id": 2,
    "label": "Aa",
    "key": "Aa"
  }, {
    "id": 3,
    "label": "Bb",
    "key": "Bb"
  }, {
    "id": 4,
    "label": "Cc",
    "key": "Cc"
  }, {
    "id": 5,
    "label": "Dd",
    "key": "Dd"
  }, {
    "id": 6,
    "label": "Ee",
    "key": "Ee"
  }, {
    "id": 7,
    "label": "Ëë",
    "key": "Ëë"
  }, {
    "id": 8,
    "label": "Gg",
    "key": "Gg"
  }, {
    "id": 9,
    "label": "Ii",
    "key": "Ii"
  }, {
    "id": 10,
    "label": "Ïï",
    "key": "Ïï"
  }, {
    "id": 11,
    "label": "Jj",
    "key": "Jj"
  }, {
    "id": 12,
    "label": "Kk",
    "key": "Kk"
  }, {
    "id": 32,
    "label": "Ll",
    "key": "Ll"
  }, {
    "id": 14,
    "label": "Mm",
    "key": "Mm"
  }, {
    "id": 15,
    "label": "Nn",
    "key": "Nn"
  }, {
     "id": 16,
    "label": "Ngng",
    "key": "Ngng"
  }, {
    "id": 17,
    "label": "Nyny",
    "key": "Nyny"
  }, {
    "id": 18,
    "label": "Oo",
    "key": "Oo"
  }, {
    "id": 19,
    "label": "Öö",
    "key": "Öö"
  }, {
    "id": 20,
    "label": "Pp",
    "key": "Pp"
  }, {
    "id": 21,
    "label": "Rr",
    "key": "Rr"
  }, {
    "id": 22,
    "label": "Tt",
    "key": "Tt"
  }, {
    "id": 23,
    "label": "Uu",
    "key": "Uu"
  }, {
    "id": 24,
    "label": "Üü",
    "key": "Üü"
  }, {
    "id": 25,
    "label": "Ww",
    "key": "Ww"
  }, {
    "id": 26,
    "label": "Yy",
    "key": "Yy"
  }, {
    "id": 27,
    "label": "Outro",
    "key": "Outro"
  }]
};